# ML Laborator 1

 ## ex 1
Se dau următoarele 9 imagini de dimensiuni 400x600. Valorile acestora au fost
salvate în fișierele “images/car_{idx}.npy”.

a. Citiți imaginile din aceste fișiere și salvați-le într-un np.array (va avea
dimensiunea 9x400x600).

In [5]:
import numpy as np

images=np.zeros((9,400,600))
for i in range(0,9):
    img=np.load("images/car_"+str(i)+".npy")
    images[i]=img
print(images)





[[[200. 200. 200. ... 204. 204. 204.]
  [199. 199. 199. ... 204. 204. 204.]
  [197. 197. 197. ... 204. 204. 204.]
  ...
  [102.  96.  95. ... 109. 111. 111.]
  [ 86.  81.  80. ... 103. 105. 111.]
  [ 83.  82.  81. ...  97.  97. 104.]]

 [[123. 123. 123. ... 178. 178. 178.]
  [123. 123. 123. ... 179. 179. 179.]
  [125. 125. 125. ... 183. 183. 183.]
  ...
  [101.  76.  80. ... 138. 122. 142.]
  [ 93.  70.  67. ... 130.  99. 139.]
  [ 80.  76.  78. ... 133. 107. 146.]]

 [[255. 255. 252. ... 253. 254. 253.]
  [255. 255. 253. ... 254. 254. 253.]
  [251. 255. 255. ... 253. 252. 251.]
  ...
  [255. 253. 255. ... 254. 252. 255.]
  [254. 251. 254. ... 254. 252. 254.]
  [255. 251. 252. ... 254. 253. 252.]]

 ...

 [[ 22.  22.  22. ... 191. 191. 191.]
  [ 22.  22.  22. ... 193. 193. 193.]
  [ 25.  25.  25. ... 195. 195. 195.]
  ...
  [ 25.  23.  21. ...  34.  34.  34.]
  [ 20.  22.  23. ...  34.  34.  34.]
  [ 19.  18.  18. ...  34.  34.  34.]]

 [[196. 196. 197. ... 254. 254. 254.]
  [196. 196.

b. Calculați suma valorilor pixelilor tuturor imaginilor.
